apiVersion: v1
kind: Service
metadata:
  name: {{ template "k8s-anomaly-detector.fullname" . }}
  labels:
    app: {{ template "k8s-anomaly-detector.name" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.queryPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "k8s-anomaly-detector.name" . }}
    release: {{ .Release.Name }}
