apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: {{ template "k8s-anomaly-detector.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       {{ template "k8s-anomaly-detector.fullname" . }}
  updatePolicy:
    updateMode: "Auto"
